const { app } = require('@azure/functions');
const https = require('https');

const SALES_EMAIL = 'Sales1@trustdi.com';

// Sends one email via Resend API
function sendEmail(apiKey, to, subject, html, fromName) {
  const from = fromName
      ? `${fromName} <Sales1@trustdi.com>`
          : 'TrustDigital <Sales1@trustdi.com>';

            const data = JSON.stringify({
                from,
                    to: Array.isArray(to) ? to : [to],
                        subject,
                            html
                              });

                                return new Promise((resolve, reject) => {
                                    const options = {
                                          hostname: 'api.resend.com',
                                                path: '/emails',
                                                      method: 'POST',
                                                            headers: {
                                                                    'Authorization': `Bearer ${apiKey}`,
                                                                            'Content-Type': 'application/json',
                                                                                    'Content-Length': Buffer.byteLength(data)
                                                                                          }
                                                                                              };

                                                                                                  const req = https.request(options, (res) => {
                                                                                                        let body = '';
                                                                                                              res.on('data', chunk => body += chunk);
                                                                                                                    res.on('end', () => resolve({ status: res.statusCode, body }));
                                                                                                                        });
                                                                                                                        
                                                                                                                            req.on('error', reject);
                                                                                                                                req.write(data);
                                                                                                                                    req.end();
                                                                                                                                      });
                                                                                                                                      }
                                                                                                                                      
                                                                                                                                      app.http('send-report', {
                                                                                                                                        methods: ['GET', 'POST'],
                                                                                                                                          authLevel: 'anonymous',
                                                                                                                                            route: 'send-report',
                                                                                                                                              handler: async (request, context) => {
                                                                                                                                                  if (request.method === 'OPTIONS') {
                                                                                                                                                        return {
                                                                                                                                                                status: 204,
                                                                                                                                                                        headers: {
                                                                                                                                                                                  'Access-Control-Allow-Origin': '*',
                                                                                                                                                                                            'Access-Control-Allow-Methods': 'POST, OPTIONS',
                                                                                                                                                                                                      'Access-Control-Allow-Headers': 'Content-Type'
                                                                                                                                                                                                              }
                                                                                                                                                                                                                    };
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        
                                                                                                                                                                                                                            let payload;
                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                      payload = await request.json();
                                                                                                                                                                                                                                          } catch (e) {
                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                        status: 400,
                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                        body: JSON.stringify({ error: 'Invalid JSON body' })
                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                      const { contact, emailHTML } = payload || {};
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                          if (!contact || !contact.email || !emailHTML) {
                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                        status: 400,
                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({ error: 'Missing required fields' })
                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      const apiKey = process.env.RESEND_API_KEY;
                                                                                                                                                                                                                                                                                                                                          if (!apiKey) {
                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                        status: 500,
                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({ error: 'Email service not configured' })
                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                      const company = contact.company || 'Your Company';
                                                                                                                                                                                                                                                                                                                                                                                          const name    = contact.name    || '';
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                              const customerSubject = `Your Microsoft 365 Licensing Report — ${company}`;
                                                                                                                                                                                                                                                                                                                                                                                                  const salesSubject    = `New M365 Report — ${company} (${name})`;
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                            await sendEmail(apiKey, contact.email, customerSubject, emailHTML, 'TrustDigital');
                                                                                                                                                                                                                                                                                                                                                                                                                  await sendEmail(apiKey, SALES_EMAIL, salesSubject, emailHTML, 'TrustDigital Calculator');
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                status: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Access-Control-Allow-Origin': '*'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            body: JSON.stringify({ success: true })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ success: false, error: err.message })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
